// src/lib/components/controls/ThermostatDial.svelte

<script lang="ts">
    import { appState } from '$state/app.svelte';
    import type { ColorScheme } from '$types';

    let { 
        min, max, value, current, hvacAction, 
        idleLabelColor, heatingLabelColor, coolingLabelColor, 
        onChange 
    } = $props<{
        min: number; max: number; value: number; current: number; 
        hvacAction: string; 
        idleLabelColor?: string; heatingLabelColor?: string; coolingLabelColor?: string;
        onChange: (val: number) => void;
    }>();

    const SIZE = 200;
    const CENTER = SIZE / 2;
    const STROKE = 20;
    const RADIUS = (SIZE - STROKE) / 2;
    const START_ANGLE = 135;
    const END_ANGLE = 405;

    // Helper: Polar to Cartesian
    function p2c(angle: number) {
        const rad = ((angle - 90) * Math.PI) / 180.0;
        return {
            x: CENTER + RADIUS * Math.cos(rad),
            y: CENTER + RADIUS * Math.sin(rad)
        };
    }

    // Helper: Describe Arc
    function describeArc(start: number, end: number) {
        const s = p2c(end);
        const e = p2c(start);
        const large = end - start <= 180 ? '0' : '1';
        return `M ${s.x} ${s.y} A ${RADIUS} ${RADIUS} 0 ${large} 0 ${e.x} ${e.y}`;
    }

    // Handle position
    let valueAngle = $derived.by(() => {
        const range = max - min;
        const ratio = (value - min) / range;
        return ratio * (END_ANGLE - START_ANGLE) + START_ANGLE;
    });

    let handlePos = $derived(p2c(valueAngle));

    // Interaction
    function handlePointer(e: PointerEvent) {
        const rect = (e.currentTarget as Element).closest('svg')!.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        
        let deg = (Math.atan2(y - CENTER, x - CENTER) * 180) / Math.PI + 90;
        if (deg < 0) deg += 360;

        // Clamping logic
        if (deg > 45 && deg < 135) {
            // closer to start or end?
            deg = Math.abs(deg - 135) < Math.abs(deg - 45) ? START_ANGLE : END_ANGLE;
        } else if (deg >= 0 && deg <= 45) {
            deg += 360; // normalize for end range
        }

        const range = max - min;
        const arc = END_ANGLE - START_ANGLE;
        const ratio = (Math.min(Math.max(deg, START_ANGLE), END_ANGLE) - START_ANGLE) / arc;
        
        const newValue = Math.round((ratio * range + min) * 10) / 10;
        if (newValue !== value) onChange(newValue);
    }

    let isDragging = false;
</script>

<div class="relative w-full h-full flex items-center justify-center select-none">
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <svg 
        viewBox="0 0 {SIZE} {SIZE}" 
        class="w-full h-full touch-none"
        onpointerdown={(e) => { e.currentTarget.setPointerCapture(e.pointerId); isDragging = true; handlePointer(e); }}
        onpointermove={(e) => { if(isDragging) handlePointer(e); }}
        onpointerup={(e) => { e.currentTarget.releasePointerCapture(e.pointerId); isDragging = false; }}
    >
        <!-- Track -->
        <path d={describeArc(START_ANGLE, END_ANGLE)} fill="none" stroke="var(--border-color-card)" stroke-width={STROKE} stroke-linecap="round" />
        
        <!-- Value Arc (Gradient) -->
        <defs>
            <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stop-color="#3b82f6" />
                <stop offset="50%" stop-color="#8b5cf6" />
                <stop offset="100%" stop-color="#ef4444" />
            </linearGradient>
        </defs>
        <path d={describeArc(START_ANGLE, valueAngle)} fill="none" stroke="url(#grad)" stroke-width={STROKE} stroke-linecap="round" />

        <!-- Handle -->
        <circle cx={handlePos.x} cy={handlePos.y} r={STROKE/2 + 2} fill="white" stroke="rgba(0,0,0,0.1)" stroke-width="1" class="shadow-md" />
    </svg>

    <div class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
        <span class="text-xs font-bold tracking-wider" style="color: {hvacAction === 'heating' ? 'var(--thermo-heat)' : 'var(--thermo-label)'}">
            {hvacAction.toUpperCase()}
        </span>
        <span class="text-4xl font-light tabular-nums" style="color: var(--text-value)">
            {value.toFixed(1)}
        </span>
    </div>
</div>

// components/ThermostatDial.tsx

import React, { useRef, useCallback } from 'react';

// --- Helper Functions ---
const polarToCartesian = (centerX: number, centerY: number, radius: number, angleInDegrees: number) => {
  const angleInRadians = ((angleInDegrees - 90) * Math.PI) / 180.0;
  return {
    x: centerX + radius * Math.cos(angleInRadians),
    y: centerY + radius * Math.sin(angleInRadians),
  };
};

const describeArc = (x: number, y: number, radius: number, startAngle: number, endAngle: number) => {
  const start = polarToCartesian(x, y, radius, endAngle);
  const end = polarToCartesian(x, y, radius, startAngle);
  const largeArcFlag = endAngle - startAngle <= 180 ? '0' : '1';
  return `M ${start.x} ${start.y} A ${radius} ${radius} 0 ${largeArcFlag} 0 ${end.x} ${end.y}`;
};

const valueToAngle = (value: number, min: number, max: number, startAngle: number, endAngle: number) => {
  const range = max - min;
  if (range === 0) return startAngle;
  const valueRatio = (value - min) / range;
  return valueRatio * (endAngle - startAngle) + startAngle;
};

// --- Component Props ---
interface ThermostatDialProps {
  min: number;
  max: number;
  value: number; // Target temperature
  current: number; // Current temperature
  onChange: (value: number) => void;
  hvacAction: string;
}

const ThermostatDial: React.FC<ThermostatDialProps> = ({ min, max, value, current, onChange, hvacAction }) => {
  const svgRef = useRef<SVGSVGElement>(null);
  
  const SIZE = 200;
  const STROKE_WIDTH = 20;
  const RADIUS = SIZE / 2 - STROKE_WIDTH / 2;
  const CENTER = SIZE / 2;
  const START_ANGLE = 135;
  const END_ANGLE = 405;

  const handlePointerMove = useCallback((e: PointerEvent) => {
    if (!svgRef.current) return;
    const rect = svgRef.current.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const angleRad = Math.atan2(y - CENTER, x - CENTER);
    let angleDeg = (angleRad * 180) / Math.PI + 90;
    if (angleDeg < 0) angleDeg += 360;

    // Clamp angle to the allowed range
    if (angleDeg < START_ANGLE && angleDeg > END_ANGLE - 360) {
      const distToStart = Math.abs(angleDeg - START_ANGLE);
      const distToEnd = Math.abs(angleDeg - (END_ANGLE - 360));
      angleDeg = distToStart < distToEnd ? START_ANGLE : END_ANGLE;
    }
    
    const range = max - min;
    const angleRange = END_ANGLE - START_ANGLE;
    const valueRatio = (angleDeg - START_ANGLE) / angleRange;
    const newValue = Math.round((valueRatio * range + min) * 2) / 2; // Round to nearest 0.5
    
    if (newValue >= min && newValue <= max) {
      onChange(newValue);
    }
  }, [CENTER, START_ANGLE, END_ANGLE, min, max, onChange]);


  const handlePointerDown = useCallback((e: React.PointerEvent) => {
    e.preventDefault();
    (e.target as HTMLElement).setPointerCapture(e.pointerId);

    const handlePointerUp = () => {
      (e.target as HTMLElement).releasePointerCapture(e.pointerId);
      window.removeEventListener('pointermove', handlePointerMove);
      window.removeEventListener('pointerup', handlePointerUp);
    };

    window.addEventListener('pointermove', handlePointerMove);
    window.addEventListener('pointerup', handlePointerUp);
    
    // Trigger first move immediately
     handlePointerMove(e.nativeEvent);
  }, [handlePointerMove]);


  const valueAngle = valueToAngle(value, min, max, START_ANGLE, END_ANGLE);
  const handlePosition = polarToCartesian(CENTER, CENTER, RADIUS, valueAngle);

  const getLabelAndColor = () => {
    switch (hvacAction) {
      case 'cooling': return { label: 'ОХЛАЖДЕНИЕ', color: '#2563eb' };
      case 'heating': return { label: 'НАГРЕВ', color: '#f97316' };
      default: return { label: 'ЦЕЛЬ', color: '#9ca3af' };
    }
  };
  const { label: centerLabel, color: activeColor } = getLabelAndColor();

  return (
    <div className="relative w-full h-full flex items-center justify-center">
      <svg
        ref={svgRef}
        viewBox={`0 0 ${SIZE} ${SIZE}`}
        className="w-full h-full"
        onPointerDown={handlePointerDown}
        style={{ touchAction: 'none' }}
      >
        <defs>
          <linearGradient id="thermoGradient" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#3b82f6" /> 
            <stop offset="50%" stopColor="#a855f7" /> 
            <stop offset="100%" stopColor="#f97316" />
          </linearGradient>
        </defs>

        {/* Background Arc */}
        <path
          d={describeArc(CENTER, CENTER, RADIUS, START_ANGLE, END_ANGLE)}
          fill="none"
          stroke="#4b5563" // gray-600
          strokeWidth={STROKE_WIDTH}
          strokeLinecap="round"
        />
        
        {/* Value Arc */}
        <path
          d={describeArc(CENTER, CENTER, RADIUS, START_ANGLE, valueAngle)}
          fill="none"
          stroke="url(#thermoGradient)"
          strokeWidth={STROKE_WIDTH}
          strokeLinecap="round"
        />

        {/* Handle */}
        <circle
          cx={handlePosition.x}
          cy={handlePosition.y}
          r={STROKE_WIDTH / 2 + 2}
          fill="#ffffff"
          className="cursor-pointer"
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
          <p className="text-xs font-bold" style={{ color: activeColor }}>{centerLabel}</p>
          <p className="text-6xl font-light text-white -my-1">{Math.round(value)}</p>
      </div>
    </div>
  );
};

export default ThermostatDial;
